apiVersion: v1
kind: Service
metadata:
  name: mediadb
  labels:
    app: mediadb
spec:
  type: ClusterIP
  selector:
    app: mediadb
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017